State.create(name: 'Aguascalientes')
State.create(name: 'Baja California')
State.create(name: 'Baja California Sur')
State.create(name: 'Campeche')
State.create(name: 'Chiapas')
State.create(name: 'Chihuahua')
State.create(name: 'Coahuila de Zaragoza')
State.create(name: 'Colima')
State.create(name: 'Durango')
State.create(name: 'Guanajuato')
State.create(name: 'Guerrero')
State.create(name: 'Hidalgo')
State.create(name: 'Jalisco')
State.create(name: 'Michoacan de Ocampo')
State.create(name: 'Morelos')
State.create(name: 'Nayarit')
State.create(name: 'Nuevo Leon')
State.create(name: 'Oaxaca')
State.create(name: 'Puebla')
State.create(name: 'Queretaro')
State.create(name: 'Quintana Roo')
State.create(name: 'San Luis Potosi')
State.create(name: 'Sinaloa')
State.create(name: 'Sonora')
State.create(name: 'Tabasco')
State.create(name: 'Tamaulipas')
State.create(name: 'Tlaxcala')
State.create(name: 'Veracruz de Ignacio de Llave')
State.create(name: 'Yucatan')
State.create(name: 'Zacatecas')
